// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.29.1
// source: api/proto/aegis/v1/telemetry.proto

package aegisv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	TelemetryService_ReportEndpointStats_FullMethodName = "/aegis.v1.TelemetryService/ReportEndpointStats"
	TelemetryService_ListEndpointHealth_FullMethodName  = "/aegis.v1.TelemetryService/ListEndpointHealth"
)

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryServiceClient interface {
	ReportEndpointStats(ctx context.Context, in *ReportEndpointStatsRequest, opts ...grpc.CallOption) (*ReportEndpointStatsResponse, error)
	ListEndpointHealth(ctx context.Context, in *ListEndpointHealthRequest, opts ...grpc.CallOption) (*ListEndpointHealthResponse, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) ReportEndpointStats(ctx context.Context, in *ReportEndpointStatsRequest, opts ...grpc.CallOption) (*ReportEndpointStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportEndpointStatsResponse)
	err := c.cc.Invoke(ctx, TelemetryService_ReportEndpointStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) ListEndpointHealth(ctx context.Context, in *ListEndpointHealthRequest, opts ...grpc.CallOption) (*ListEndpointHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEndpointHealthResponse)
	err := c.cc.Invoke(ctx, TelemetryService_ListEndpointHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility
type TelemetryServiceServer interface {
	ReportEndpointStats(context.Context, *ReportEndpointStatsRequest) (*ReportEndpointStatsResponse, error)
	ListEndpointHealth(context.Context, *ListEndpointHealthRequest) (*ListEndpointHealthResponse, error)
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTelemetryServiceServer struct {
}

func (UnimplementedTelemetryServiceServer) ReportEndpointStats(context.Context, *ReportEndpointStatsRequest) (*ReportEndpointStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportEndpointStats not implemented")
}
func (UnimplementedTelemetryServiceServer) ListEndpointHealth(context.Context, *ListEndpointHealthRequest) (*ListEndpointHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEndpointHealth not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_ReportEndpointStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportEndpointStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).ReportEndpointStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_ReportEndpointStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).ReportEndpointStats(ctx, req.(*ReportEndpointStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_ListEndpointHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEndpointHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).ListEndpointHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_ListEndpointHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).ListEndpointHealth(ctx, req.(*ListEndpointHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegis.v1.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportEndpointStats",
			Handler:    _TelemetryService_ReportEndpointStats_Handler,
		},
		{
			MethodName: "ListEndpointHealth",
			Handler:    _TelemetryService_ListEndpointHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/aegis/v1/telemetry.proto",
}
